/*
 *
 * Share constants
 *
 */

export const DEFAULT_ACTION = 'app/Share/DEFAULT_ACTION';
export const GET_COMMENTS_ACTION = 'app/Share/GET_COMMENTS_ACTION';
export const GET_COMMENTS_SUCCESSFUL_ACTION = 'app/Share/GET_COMMENTS_SUCCESSFUL_ACTION';
export const GET_COMMENTS_ERROR_ACTION = 'app/Share/GET_COMMENTS_ERROR_ACTION';
export const UPDATE_NETWORK_ACTIVITY_ACTION = 'app/Share/UPDATE_NETWORK_ACTIVITY_ACTION';
