/*
 *
 * Share constants
 *
 */

export const DEFAULT_ACTION = 'app/Share/DEFAULT_ACTION';
export const GET_COMMENTS_ACTION = 'app/Share/GET_COMMENTS_ACTION';
export const GET_COMMENTS_SUCCESSFUL_ACTION = 'app/Share/GET_COMMENTS_SUCCESSFUL_ACTION';
export const GET_COMMENTS_ERROR_ACTION = 'app/Share/GET_COMMENTS_ERROR_ACTION';
export const UPDATE_NETWORK_ACTIVITY_ACTION = 'app/Share/UPDATE_NETWORK_ACTIVITY_ACTION';
export const TYPE_TEXT_ACTION = 'app/Share/TYPE_TEXT_ACTION';
export const SUBMIT_STORY_VALIDATION_ERROR = 'app/Share/SUBMIT_STORY_VALIDATION_ERROR';
export const RECAPTCHA_ERROR_ACTION = 'app/Share/RECAPTCHA_ERROR_ACTION';
export const SUBMIT_STORY_ACTION = 'app/Share/SUBMIT_STORY_ACTION';
export const UPDATE_RECAPTCHA_ACTION = 'app/Share/UPDATE_RECAPTCHA_ACTION';
export const POST_COMMENT_SUCCESSFUL_ACTION = 'app/Share/POST_COMMENT_SUCCESSFUL_ACTION';
export const CLOSE_EDITOR_ACTION = 'app/Share/CLOSE_EDITOR_ACTION';
export const DISPLAY_EDITOR_ACTION = 'app/Share/DISPLAY_EDITOR_ACTION';
