/*
 *
 * About constants
 *
 */

export const DEFAULT_ACTION = 'app/About/DEFAULT_ACTION';
export const DISPLAY_MODAL_ACTION = 'app/About/DISPLAY_MODAL_ACTION';
export const HIDE_MODAL_ACTION = 'app/About/HIDE_MODAL_ACTION';
export const UPDATE_FIELD_ACTION = 'app/About/UPDATE_FIELD_ACTION';
export const SUBMIT_FORM_ACTION = 'app/About/SUBMIT_FORM_ACTION';
export const VALIDATION_ERRORS_ACTION = 'app/About/VALIDATION_ERRORS_ACTION';
export const CONTACT_FORM_RECEIVED_ACTION = 'app/About/CONTACT_FORM_RECEIVED_ACTION';
export const CONTACT_FORM_REMOVE_MESSAGE_ACTION = 'app/About/CONTACT_FORM_REMOVE_MESSAGE_ACTION'
