/*
 *
 * Register constants
 *
 */

export const SUBMIT_REGISTRATION_ACTION =
  'app/Register/SUBMIT_REGISTRATION_ACTION';
export const UPDATE_FIELD_ACTION = 'app/Register/UPDATE_FIELD_ACTION';
export const UPDATE_FIELD_VALIDATION_ACTION =
  'app/Register/UPDATE_FIELD_VALIDATION_ACTION';
export const REGISTRATION_SUCCESSFUL_ACTION = 'app/Register/REGISTRATION_SUCCESSFUL_ACTION';
export const REGISTRATION_MESSAGE_ACTION = 'app/Register/REGISTRATION_MESSAGE_ACTION';
