/*
 *
 * Story constants
 *
 */

export const GET_STORY_ACTION = 'app/Story/GET_STORY_ACTION';
export const GET_STORY_SUCCESS_ACTION = 'app/Story/GET_STORY_SUCCESS_ACTION';
export const GET_STORY_ERROR_ACTION='app/Story/GET_STORY_ERROR_ACTION';
export const TYPE_TEXT_ACTION = 'app/Story/TYPE_TEXT_ACTION';
export const RECAPTCHA_ERROR_ACTION = 'app/Story/RECAPTCHA_ERROR_ACTION';
export const UPDATE_RECAPTCHA_ACTION = 'app/Story/UPDATE_RECAPTCHA_ACTION';
export const UPDATE_NETWORK_ACTIVITY_ACTION = 'app/Story/UPDATE_NETWORK_ACTIVITY_ACTION';
